    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: SAST,SCA
        polaris_application_name: chuckaude-${{ github.event.repository.name }}
        polaris_fixpr_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
